---
resource_types:
  - name: github-token-resource
    type: registry-image
    source:
      repository: ghcr.io/tenjaa/concourse-github-app-token
  - name: cron-resource
    type: registry-image
    check_every: 20m
    source:
      repository: governmentdigitalservice/pay-cron-resource
resources:
  - name: github-token
    type: github-token-resource
    source:
      appId: "((github-app.id))"
      privateKey: "((github-app.private-key))"
      user: samsimpson1
  - name: pipelines-git
    type: git
    source:
      uri: https://github.com/samsimpson1/pipelines.git
      branch: main
  - name: cron-trigger
    type: cron-resource
    source:
      expression: "37 */2 * * *"
      location: "Europe/London"
      fire_immediately: true
jobs:
  - name: renovate
    plan:
      - get: cron-trigger
        trigger: true
      - put: github-token
      - load_var: github-token
        file: github-token/token
      - get: pipelines-git
      - task: run-renovate
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/renovatebot/renovate
              tag: "41.156"
          inputs:
            - name: pipelines-git
          run:
            path: renovate
          params:
            RENOVATE_CONFIG_FILE: "pipelines-git/renovate/config.json"
            RENOVATE_PLATFORM: "github"
            RENOVATE_TOKEN: "((.:github-token))"
            RENOVATE_AUTODISCOVER: "false"