---
resource_types:
  - name: github-token
    type: registry-image
    source:
      repository: ghcr.io/tenjaa/concourse-github-app-token
resources:
  - name: github-token
    type: github-token
    source:
      appId: "((github-app.id))"
      privateKey: "((github-app.private-key))"
      user: samsimpson1
  - name: pipelines-git
    type: git
    source:
      uri: https://github.com/samsimpson1/pipelines.git
      branch: main
jobs:
  - name: renovate
    plan:
      - put: github-token
      - load_var: github-token
        file: github-token/token
      - get: pipelines-git
      - task: run-renovate
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ghcr.io/renovatebot/renovate
              tag: "41.156"
          inputs:
            - name: pipelines-git
          run:
            path: renovate
          params:
            RENOVATE_CONFIG_FILE: "pipelines-git/renovate/config.json"
            RENOVATE_PLATFORM: "github"
            RENOVATE_TOKEN: "((.:github-token))"
            RENOVATE_AUTODISCOVER: "false"