resources:
  - name: pipelines-repo
    type: git
    source:
      uri: https://github.com/samsimpson1/pipelines
      branch: main
jobs:
  - name: configure-pipelines
    plan:
      - get: pipelines-repo
        trigger: true
      # main pipeline
      - set_pipeline: configure-pipelines
        file: pipelines-repo/configure-pipelines.yaml
      # ansible
      - set_pipeline: ansible-lint
        file: pipelines-repo/ansible/ansible-lint.yaml
      - set_pipeline: ansible-container-build
        file: pipelines-repo/ansible/ansible-container-build.yaml
      - set_pipeline: ansible-deploy
        file: pipelines-repo/ansible/ansible-deploy.yaml
      # terraform
      - set_pipeline: terraform-public
        file: pipelines-repo/terraform/terraform-public.yaml
      # renovate
      - set_pipeline: renovate-github
        file: pipelines-repo/renovate/github.yaml
      - set_pipeline: renovate-forgejo
        file: pipelines-repo/renovate/forgejo.yaml
      # concourse resources
      - set_pipeline: forgejo-commit-resource-build
        file: pipelines-repo/concourse-resources/forgejo-commit-resource-build.yaml
      # misc
      - set_pipeline: notes-agent-image
        file: pipelines-repo/notes-agent-image/pipeline.yaml
      - set_pipeline: obsidian-headless-image
        file: pipelines-repo/obsidian-headless-image/pipeline.yaml
      - set_pipeline: storage-box-metrics-image
        file: pipelines-repo/storage-box-metrics-image/pipeline.yaml
      - set_pipeline: stonks-scraper-image
        file: pipelines-repo/stonks-scraper-image/pipeline.yaml
      - set_pipeline: pi-tracker
        file: pipelines-repo/pi/tracker.yaml
