---
resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: cfcommunity/github-pr-resource
resources:
  - name: pull-request
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook.token))
    source:
      repository: samsimpson1/terraform-public
      access_token: ((github-pr-status.token))
  - name: main
    type: git
    check_every: 5m
    source:
      uri: https://github.com/samsimpson1/terraform-public
      branch: main
jobs:
  - name: terraform-apply
    plan:
      - get: main
        trigger: true
      - task: run-terraform-apply
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
              tag: "latest"
          inputs:
            - name: main
          run:
            path: /bin/sh
            args:
              - "-c"
              - |
                cd main && \
                  terraform init && \
                  terraform apply -auto-approve
          params:
            VAULT_ADDR: "https://vault.int.simpson.id"
            VAULT_TOKEN: "((vault-webhook-read.token))"
            AWS_ACCESS_KEY_ID: "((terraform-state-bucket-access.aws_access_key_id))"
            AWS_SECRET_ACCESS_KEY: "((terraform-state-bucket-access.aws_secret_access_key))"
            GITHUB_TOKEN: "((github.token))"
  - name: terraform-plan
    plan:
      - get: pull-request
        trigger: true
        version: every
      - put: pull-request
        params:
          path: pull-request
          status: pending
      - task: run-terraform-plan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
              tag: "latest"
          inputs:
            - name: pull-request
          run:
            path: /bin/sh
            args:
              - "-c"
              - |
                cd pull-request && \
                  terraform init && \
                  terraform plan
          params:
            VAULT_ADDR: "https://vault.int.simpson.id"
            VAULT_TOKEN: "((vault-webhook-read.token))"
            AWS_ACCESS_KEY_ID: "((terraform-state-bucket-access.aws_access_key_id))"
            AWS_SECRET_ACCESS_KEY: "((terraform-state-bucket-access.aws_secret_access_key))"
            GITHUB_TOKEN: "((github.token))"
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - put: pull-request
        params:
          path: pull-request
          status: success
