# TODO: remove this resource type once the version_type change has been released
# https://github.com/concourse/git-resource/pull/474
resource_types:
  - name: git
    type: registry-image
    source:
      repository: concourse/git-resource
      tag: dev
resources:
  - name: branches
    check_every: 20m0s
    type: git
    source:
      version_type: branches
      uri: https://git.sams.wtf/things/pi.git
  - name: pipelines-repo
    type: git
    source:
      uri: https://github.com/samsimpson1/pipelines
      branch: main
jobs:
  - name: tracker
    plan:
      - get: branches
        trigger: true
      - get: pipelines-repo
      - load_var: list
        file: branches/branches.json
      - across:
          - var: branch
            values: ((.:list))
        set_pipeline: pi-test
        file: pipelines-repo/pi/pipeline.yaml
        instance_vars: { branch: ((.:branch)) }
